// src/app_data.rs — Static + Flathub-sourced catalog data

use serde::{Deserialize, Serialize};

/// Raw application record (populated from Flathub JSON or local catalog).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppRecord {
    pub id: String,
    pub flatpak_id: String,
    pub name: String,
    pub summary: String,
    pub description: String,
    pub version: String,
    pub developer: String,
    pub category: String,
    pub icon_letter: String,
    pub icon_color_hex: String,
    pub rating: f32,
    pub download_count: String,
    pub size_mb: f32,
}

/// Hard-coded catalog — seed data shown before Flathub metadata is fetched.
pub fn builtin_catalog() -> Vec<AppRecord> {
    vec![
        AppRecord {
            id: "firefox".into(),
            flatpak_id: "org.mozilla.firefox".into(),
            name: "Firefox".into(),
            summary: "Fast, private & secure web browser".into(),
            description: "Mozilla Firefox is a free and open-source web browser. It is known for its speed, privacy features, and extensive library of extensions.".into(),
            version: "126.0".into(),
            developer: "Mozilla".into(),
            category: "internet".into(),
            icon_letter: "F".into(),
            icon_color_hex: "#e25c00".into(),
            rating: 4.7,
            download_count: "2.1M".into(),
            size_mb: 218.0,
        },
        AppRecord {
            id: "vlc".into(),
            flatpak_id: "org.videolan.VLC".into(),
            name: "VLC".into(),
            summary: "The ultimate open source media player".into(),
            description: "VLC is a free and open-source cross-platform multimedia player that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.".into(),
            version: "3.0.20".into(),
            developer: "VideoLAN".into(),
            category: "multimedia".into(),
            icon_letter: "V".into(),
            icon_color_hex: "#e8861a".into(),
            rating: 4.8,
            download_count: "1.8M".into(),
            size_mb: 55.0,
        },
        AppRecord {
            id: "vscode".into(),
            flatpak_id: "com.visualstudio.code".into(),
            name: "VS Code".into(),
            summary: "Powerful code editor by Microsoft".into(),
            description: "Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux.".into(),
            version: "1.90.0".into(),
            developer: "Microsoft".into(),
            category: "development".into(),
            icon_letter: "C".into(),
            icon_color_hex: "#007acc".into(),
            rating: 4.9,
            download_count: "3.2M".into(),
            size_mb: 340.0,
        },
        AppRecord {
            id: "gimp".into(),
            flatpak_id: "org.gimp.GIMP".into(),
            name: "GIMP".into(),
            summary: "Professional image editing suite".into(),
            description: "GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows and more. Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you with sophisticated tools.".into(),
            version: "2.10.38".into(),
            developer: "The GIMP Team".into(),
            category: "graphics".into(),
            icon_letter: "G".into(),
            icon_color_hex: "#5c8926".into(),
            rating: 4.5,
            download_count: "980K".into(),
            size_mb: 270.0,
        },
        AppRecord {
            id: "obs".into(),
            flatpak_id: "com.obsproject.Studio".into(),
            name: "OBS Studio".into(),
            summary: "Free streaming & recording software".into(),
            description: "OBS Studio is free and open source software for video recording and live streaming. Stream to Twitch, YouTube and many other providers.".into(),
            version: "30.1.2".into(),
            developer: "OBS Project".into(),
            category: "multimedia".into(),
            icon_letter: "O".into(),
            icon_color_hex: "#6441a5".into(),
            rating: 4.8,
            download_count: "1.2M".into(),
            size_mb: 190.0,
        },
        AppRecord {
            id: "libreoffice".into(),
            flatpak_id: "org.libreoffice.LibreOffice".into(),
            name: "LibreOffice".into(),
            summary: "Complete office productivity suite".into(),
            description: "LibreOffice is a powerful and free office suite, used by millions of people around the world. Its clean interface and feature-rich tools help you unleash your creativity.".into(),
            version: "24.2.3".into(),
            developer: "The Document Foundation".into(),
            category: "productivity".into(),
            icon_letter: "L".into(),
            icon_color_hex: "#18a303".into(),
            rating: 4.4,
            download_count: "1.5M".into(),
            size_mb: 880.0,
        },
        AppRecord {
            id: "inkscape".into(),
            flatpak_id: "org.inkscape.Inkscape".into(),
            name: "Inkscape".into(),
            summary: "Professional vector graphics editor".into(),
            description: "Inkscape is a professional vector graphics editor for Linux, Windows, and macOS. It's free and open source. Inkscape uses the standardized SVG file format as its main format.".into(),
            version: "1.3.2".into(),
            developer: "Inkscape Team".into(),
            category: "graphics".into(),
            icon_letter: "I".into(),
            icon_color_hex: "#000000".into(),
            rating: 4.6,
            download_count: "620K".into(),
            size_mb: 120.0,
        },
        AppRecord {
            id: "signal".into(),
            flatpak_id: "org.signal.Signal".into(),
            name: "Signal".into(),
            summary: "Private, encrypted messenger".into(),
            description: "Signal is a cross-platform encrypted messaging service. The Signal app uses the Internet to send one-to-one and group messages with end-to-end encryption.".into(),
            version: "7.12.0".into(),
            developer: "Signal Foundation".into(),
            category: "internet".into(),
            icon_letter: "S".into(),
            icon_color_hex: "#3a76f0".into(),
            rating: 4.7,
            download_count: "890K".into(),
            size_mb: 145.0,
        },
        AppRecord {
            id: "blender".into(),
            flatpak_id: "org.blender.Blender".into(),
            name: "Blender".into(),
            summary: "3D creation suite: model, rig, render".into(),
            description: "Blender is a free and open-source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing, and motion tracking.".into(),
            version: "4.1.1".into(),
            developer: "Blender Foundation".into(),
            category: "graphics".into(),
            icon_letter: "B".into(),
            icon_color_hex: "#ea7600".into(),
            rating: 4.9,
            download_count: "1.1M".into(),
            size_mb: 430.0,
        },
        AppRecord {
            id: "steam".into(),
            flatpak_id: "com.valvesoftware.Steam".into(),
            name: "Steam".into(),
            summary: "The ultimate gaming platform".into(),
            description: "Steam is a video game digital distribution service and storefront by Valve. It was launched as a software client in September 2003 to provide game updates automatically.".into(),
            version: "latest".into(),
            developer: "Valve".into(),
            category: "games".into(),
            icon_letter: "S".into(),
            icon_color_hex: "#1b2838".into(),
            rating: 4.6,
            download_count: "4.5M".into(),
            size_mb: 380.0,
        },
        AppRecord {
            id: "kdenlive".into(),
            flatpak_id: "org.kde.kdenlive".into(),
            name: "Kdenlive".into(),
            summary: "Non-linear video editor".into(),
            description: "Kdenlive is a powerful free and open-source video editor based on the MLT framework. It features multi-track editing, an animated clip-monitor, and extensive effects.".into(),
            version: "24.02.2".into(),
            developer: "KDE".into(),
            category: "multimedia".into(),
            icon_letter: "K".into(),
            icon_color_hex: "#2196f3".into(),
            rating: 4.3,
            download_count: "450K".into(),
            size_mb: 250.0,
        },
        AppRecord {
            id: "thunderbird".into(),
            flatpak_id: "org.mozilla.Thunderbird".into(),
            name: "Thunderbird".into(),
            summary: "Free email, calendar, and chat client".into(),
            description: "Mozilla Thunderbird is a free email application that's easy to set up and customize. It also features an integrated chat client, address book, and calendar.".into(),
            version: "115.11.0".into(),
            developer: "Mozilla".into(),
            category: "internet".into(),
            icon_letter: "T".into(),
            icon_color_hex: "#0a84ff".into(),
            rating: 4.3,
            download_count: "760K".into(),
            size_mb: 200.0,
        },
        AppRecord {
            id: "bottles".into(),
            flatpak_id: "com.usebottles.bottles".into(),
            name: "Bottles".into(),
            summary: "Run Windows software on Linux".into(),
            description: "Bottles lets you run Windows software on Linux using Wine. It features an easy-to-use interface with support for multiple environments, dependencies, and installers.".into(),
            version: "51.13".into(),
            developer: "Bottles Contributors".into(),
            category: "tools".into(),
            icon_letter: "B".into(),
            icon_color_hex: "#9b59b6".into(),
            rating: 4.5,
            download_count: "530K".into(),
            size_mb: 95.0,
        },
        AppRecord {
            id: "flatseal".into(),
            flatpak_id: "com.github.tchx84.Flatseal".into(),
            name: "Flatseal".into(),
            summary: "Manage Flatpak application permissions".into(),
            description: "Flatseal is a graphical utility to review and modify permissions from your Flatpak applications. It makes it easy to lock down or expand sandbox access.".into(),
            version: "2.2.0".into(),
            developer: "tchx84".into(),
            category: "tools".into(),
            icon_letter: "F".into(),
            icon_color_hex: "#4caf50".into(),
            rating: 4.7,
            download_count: "310K".into(),
            size_mb: 8.0,
        },
        AppRecord {
            id: "celluloid".into(),
            flatpak_id: "io.github.celluloid_player.Celluloid".into(),
            name: "Celluloid".into(),
            summary: "Simple mpv frontend for GNOME".into(),
            description: "Celluloid is a simple GTK+ frontend for mpv. It aims to be easy to use while maintaining high level of configurability.".into(),
            version: "0.26".into(),
            developer: "gnome-mpv Contributors".into(),
            category: "multimedia".into(),
            icon_letter: "C".into(),
            icon_color_hex: "#e91e63".into(),
            rating: 4.4,
            download_count: "200K".into(),
            size_mb: 12.0,
        },
        AppRecord {
            id: "helix".into(),
            flatpak_id: "com.helix_editor.Helix".into(),
            name: "Helix".into(),
            summary: "A post-modern modal text editor".into(),
            description: "Helix is a Kakoune / Neovim inspired editor written in Rust. It features a built-in language server protocol support, tree-sitter integration, and multiple selections.".into(),
            version: "24.03".into(),
            developer: "Helix Contributors".into(),
            category: "development".into(),
            icon_letter: "H".into(),
            icon_color_hex: "#d946ef".into(),
            rating: 4.8,
            download_count: "180K".into(),
            size_mb: 22.0,
        },
    ]
}

pub fn builtin_categories() -> Vec<(String, String, String)> {
    // (id, label, icon)
    vec![
        ("all".into(),          "All Apps".into(),     "◈".into()),
        ("internet".into(),     "Internet".into(),      "⊕".into()),
        ("multimedia".into(),   "Multimedia".into(),    "▶".into()),
        ("graphics".into(),     "Graphics".into(),      "◉".into()),
        ("productivity".into(), "Productivity".into(),  "☰".into()),
        ("development".into(),  "Development".into(),   "⌘".into()),
        ("games".into(),        "Games".into(),         "◈".into()),
        ("tools".into(),        "Tools".into(),         "⊞".into()),
    ]
}
